directory:
  - terraform

output:
  - cli
  - json

soft-fail: true

skip-check:
  - CKV_K8S_8    # liveness probe - handled in terraform
  - CKV_K8S_9    # readiness probe - handled in terraform
  - CKV_K8S_14   # image tag - using latest for this project
  - CKV_K8S_15   # image pull policy - set to IfNotPresent
  - CKV_K8S_28   # privilege escalation - not applicable
  - CKV_K8S_30   # security context - not applicable
  - CKV_K8S_37   # read only root filesystem - not applicable

compact: true
download-external-modules: false