apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app: devsecops-app
    environment: dev
    managed-by: terraform

---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    app: devsecops-app
    environment: staging
    managed-by: terraform

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app: devsecops-app
    environment: prod
    managed-by: terraform