apiVersion: v1
kind: Service
metadata:
  name: devsecops-app-service
  namespace: default
  labels:
    app: devsecops-app
    environment: dev
spec:
  # ============================================
  # SERVICE TYPE — LoadBalancer exposes app
  # to the internet via a public IP
  # ============================================
  type: LoadBalancer

  selector:
    app: devsecops-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

  # ============================================
  # SESSION AFFINITY — keeps a user connected
  # to the same pod during their session
  # ============================================
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

---
# ============================================
# HORIZONTAL POD AUTOSCALER — automatically
# scales pods up/down based on CPU usage
# ============================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devsecops-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devsecops-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80